<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEXZBHsq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEXZBHsq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEXZBHsq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEXZBHsq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEXZBHsq\App_KernelDevDebugContainer([
    'container.build_hash' => 'EXZBHsq',
    'container.build_id' => '532460f4',
    'container.build_time' => 1675927968,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEXZBHsq');
