<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_fact' => [[], ['_controller' => 'App\\Controller\\FactController::index'], [], [['text', '/fact']], [], [], []],
    'app_fact_n' => [['n'], ['_controller' => 'App\\Controller\\FactController::showFact'], [], [['variable', '/', '[^/]++', 'n', true], ['text', '/fact']], [], [], []],
    'app_combi_n_p' => [['n', 'p'], ['_controller' => 'App\\Controller\\FactController::showCombi'], [], [['variable', '/', '[^/]++', 'p', true], ['variable', '/', '[^/]++', 'n', true], ['text', '/combi']], [], [], []],
    'app_master' => [[], ['_controller' => 'App\\Controller\\MasterController::master'], [], [['text', '/master']], [], [], []],
];
