
package hotel.web.service.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHotelService", targetNamespace = "http://services.service.web.hotel/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IHotelService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReduction", targetNamespace = "http://services.service.web.hotel/", className = "hotel.web.service.client.GetReduction")
    @ResponseWrapper(localName = "getReductionResponse", targetNamespace = "http://services.service.web.hotel/", className = "hotel.web.service.client.GetReductionResponse")
    @Action(input = "http://services.service.web.hotel/IHotelService/getReductionRequest", output = "http://services.service.web.hotel/IHotelService/getReductionResponse")
    public Integer getReduction(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rechercher", targetNamespace = "http://services.service.web.hotel/", className = "hotel.web.service.client.Rechercher")
    @ResponseWrapper(localName = "rechercherResponse", targetNamespace = "http://services.service.web.hotel/", className = "hotel.web.service.client.RechercherResponse")
    @Action(input = "http://services.service.web.hotel/IHotelService/rechercherRequest", output = "http://services.service.web.hotel/IHotelService/rechercherResponse")
    public List<String> rechercher(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserver", targetNamespace = "http://services.service.web.hotel/", className = "hotel.web.service.client.Reserver")
    @ResponseWrapper(localName = "reserverResponse", targetNamespace = "http://services.service.web.hotel/", className = "hotel.web.service.client.ReserverResponse")
    @Action(input = "http://services.service.web.hotel/IHotelService/reserverRequest", output = "http://services.service.web.hotel/IHotelService/reserverResponse")
    public String reserver(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        double arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNom", targetNamespace = "http://services.service.web.hotel/", className = "hotel.web.service.client.GetNom")
    @ResponseWrapper(localName = "getNomResponse", targetNamespace = "http://services.service.web.hotel/", className = "hotel.web.service.client.GetNomResponse")
    @Action(input = "http://services.service.web.hotel/IHotelService/getNomRequest", output = "http://services.service.web.hotel/IHotelService/getNomResponse")
    public String getNom();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAddresse", targetNamespace = "http://services.service.web.hotel/", className = "hotel.web.service.client.GetAddresse")
    @ResponseWrapper(localName = "getAddresseResponse", targetNamespace = "http://services.service.web.hotel/", className = "hotel.web.service.client.GetAddresseResponse")
    @Action(input = "http://services.service.web.hotel/IHotelService/getAddresseRequest", output = "http://services.service.web.hotel/IHotelService/getAddresseResponse")
    public String getAddresse();

    /**
     * 
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEtoiles", targetNamespace = "http://services.service.web.hotel/", className = "hotel.web.service.client.GetEtoiles")
    @ResponseWrapper(localName = "getEtoilesResponse", targetNamespace = "http://services.service.web.hotel/", className = "hotel.web.service.client.GetEtoilesResponse")
    @Action(input = "http://services.service.web.hotel/IHotelService/getEtoilesRequest", output = "http://services.service.web.hotel/IHotelService/getEtoilesResponse")
    public Integer getEtoiles();

}
