<?php

namespace ContainerEXZBHsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zov_EPNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Zov.ePN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zov.ePN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'request' => ['privates', '.errored.oleRphV', NULL, 'Cannot determine controller argument for "App\\Controller\\MasterController::master()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
            'session' => ['privates', '.errored.6Hrsag9', NULL, 'Cannot determine controller argument for "App\\Controller\\MasterController::master()": the $session argument is type-hinted with the non-existent class or interface: "App\\Controller\\SessionInterface". Did you forget to add a use statement?'],
        ], [
            'request' => '?',
            'session' => '?',
        ]);
    }
}
