<?php

namespace ContainerEXZBHsq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_6Hrsag9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.6Hrsag9' shared service.
     *
     * @return \App\Controller\SessionInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\MasterController::master()": the $session argument is type-hinted with the non-existent class or interface: "App\\Controller\\SessionInterface". Did you forget to add a use statement?');
    }
}
